### ISSUE TITLE
keras-contrib broken due to broken keras master

### ISSUE THREAD

**Issue by ahundt** [farizrahman4u/keras-contrib#164]
```
_________ ERROR collecting tests/keras_contrib/backend/backend_test.py _________
ImportError while importing test module '/home/travis/build/farizrahman4u/keras-contrib/tests/keras_contrib/backend/backend_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/keras_contrib/backend/backend_test.py:11: in <module>
    import keras_contrib.backend.tensorflow_backend as KCTF
keras_contrib/backend/tensorflow_backend.py:11: in <module>
    from keras.backend.tensorflow_backend import _postprocess_conv3d_output
E   ImportError: cannot import name _postprocess_conv3d_output
------------------------------- Captured stderr --------------------------------
2017-10-17 08:46:30.945895: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-17 08:46:30.945955: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-17 08:46:30.945962: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
============================= 39 tests deselected ==============================
=================== 39 deselected, 1 error in 46.02 seconds ====================
```
Due to this commit:
https://github.com/fchollet/keras/commit/6b106ab4ec9a1c0eb3e24ae590ce63f84022ad40#diff-a18b8c6a1191d6f49303e0d599ca8c37L3178

**Comment by tarlen5** [comment]
Thanks for flagging this issue! I ran into the same problem. Has anyone made any progress on a fix yet?

**Comment by ahundt** [comment]
@tarlen5 I think it is fixed with master of both keras and keras-contrib. I think I just moved the relevant code into keras-contrib.

**Comment by lucasdavid** [comment]
I still have this issue, installing contrib from master branch:
```
  File "/mnt/files/envs/tf/lib/python3.5/site-packages/keras_contrib/__init__.py", line 2, in <module>
    from . import backend
  File "/mnt/files/envs/tf/lib/python3.5/site-packages/keras_contrib/backend/__init__.py", line 14, in <module>
    from .tensorflow_backend import *
  File "/mnt/files/envs/tf/lib/python3.5/site-packages/keras_contrib/backend/tensorflow_backend.py", line 10, in <module>
    from keras.backend.tensorflow_backend import _postprocess_conv3d_output
ImportError: cannot import name '_postprocess_conv3d_output'
```
```shell
(tf) ldavid@jane:~$ pip freeze | grep eras
Keras==2.1.1
keras-contrib==1.2.1
```

**Comment by ahundt** [comment]
@tarlen5 @lucasdavid easiest thing to do would be to copy the function from a previous version of keras which included it. Even better would be to update the API to not need it. A pull request would be appreciated!

**Comment by lucasdavid** [comment]
The problem's gone, actually. I'm sorry, I probably misdiagnosed it.

**Comment by ahundt** [comment]
Fixed!
